In [ ]:
##numpy array and basics

In [2]:
import numpy as np

In [3]:
#printing the arrays from list
arr_1d=np.array([1,2,3,4])
print('1d array is:',arr_1d)

arr_2d=np.array([[1,2,3],[4,5,7]])
print('2d array is:',arr_2d)

1d array is: [1 2 3 4]
2d array is: [[1 2 3]
 [4 5 7]]


In [4]:
py_list=[1,2,4]
print('python list multiplication',py_list*2)

np_array=np.array([1,2,3])
print('Python array multiplication',np_array*2)

import time
start=time.time()
py_list=[i*2 for i in range(100)]
print('time for list operation is: ',time.time()-start)

start=time.time()
np_array=np.arange(100000)*2
print('time for numpy operation is: ',time.time()-start)


python list multiplication [1, 2, 4, 1, 2, 4]
Python array multiplication [2 4 6]
time for list operation is:  0.00019288063049316406
time for numpy operation is:  0.0018699169158935547


In [5]:
##creating array from scratch
zeroes=np.zeros((2,3))
print('zeroes array \n',zeroes)

ones=np.ones((2,3))
print('ones array \n',ones)

random=np.random.random((2,3))
print('random array \n',random)

sequence=np.arange(0,10,2)
print('sequence array \n',sequence)

zeroes array 
 [[0. 0. 0.]
 [0. 0. 0.]]
ones array 
 [[1. 1. 1.]
 [1. 1. 1.]]
random array 
 [[0.54207381 0.65282902 0.79782814]
 [0.66602303 0.02196874 0.01407352]]
sequence array 
 [0 2 4 6 8]


In [6]:
###Vector, Matrix and Tensor
vector=np.array([1,2])
print('Vector:\n',vector)

matrix=np.array([[1,2],[3,4]])
print('Matrix:\n',matrix)

tensor=np.array([[[1,2],[4,3]],[[3,4],[4,5]]])
print('Tensor: \n',tensor)

Vector:
 [1 2]
Matrix:
 [[1 2]
 [3 4]]
Tensor: 
 [[[1 2]
  [4 3]]

 [[3 4]
  [4 5]]]


In [7]:
###Array Properties
arr=np.array([[1,2,3],
           [4,5,6]])
print('shape:',arr.shape)
print('size',arr.size)
print('dimension:',arr.ndim)
print('type:',arr.dtype)

shape: (2, 3)
size 6
dimension: 2
type: int64


In [8]:
##Arrat Reshaping
arr=np.arange(1,13)
print('array:',arr)

reshaped=arr.reshape(3,4)
print('Reshaped Array:',reshaped)

flattened=reshaped.flatten()
print('Flattened Array:',flattened)

raveled=reshaped.ravel()
print('Raveled Array:',raveled)

transpose=reshaped.T
print('Transpose of matrix is ',transpose)

array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattened Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled Array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Transpose of matrix is  [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
