In [2]:
import numpy as np

## Numpy Array Operations

In [8]:
arr=np.arange(1,9)
print('Array Slicing: ',arr[2:7])
print('with steps: ',arr[2:7:2])
print('Negative Indexing: ',arr[-2])

Array Slicing:  [3 4 5 6 7]
with steps:  [3 5 7]
Negative Indexing:  7


In [10]:
arr_2d=np.array([
[1,2,3],
[4,5,6],
[7,8,9]])
print('Specific Element:',arr_2d[1,2])
print('Entire row ',arr_2d[1])
print('Entire Coulumn ',arr_2d[:,2])

Specific Element: 6
Entire row  [4 5 6]
Entire Coulumn  [3 6 9]


## Sorting


In [16]:
unsorted=np.array([2,4,3,8,1,55,67,31])
print('Sorted array: ',np.sort(unsorted))

arr_2d=np.array([[1,4],[2,1],[3,2]])
print('sorted array by row:', np.sort(arr_2d,axis=0))


Sorted array:  [ 1  2  3  4  8 31 55 67]
sorted array by row: [[1 1]
 [2 2]
 [3 4]]


## Filtering Array

In [22]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2==0]
print('Even numbers',even_numbers)

mask=numbers>5
print('Numbers greater than 5', numbers[mask])

Even numbers [ 2  4  6  8 10]
Numbers greater than 5 [ 6  7  8  9 10]


## Fancy indexing vs np.where()

In [26]:
indices=[0,2,4]
print(numbers[indices])

where_result=np.where(numbers>5)
print(where_result)
print('Np Where:',numbers[where_result])

condition_array=np.where(numbers>5,numbers*3,numbers)
print('consition array=',condition_array)

condition_array=np.where(numbers<5,numbers*3,numbers)
print('consition array=',condition_array)

condition_array=np.where(numbers<5,'true','false')
print('consition array=',condition_array)



[1 3 5]
(array([5, 6, 7, 8, 9]),)
Np Where: [ 6  7  8  9 10]
consition array= [ 1  2  3  4  5 18 21 24 27 30]
consition array= [ 3  6  9 12  5  6  7  8  9 10]
consition array= ['true' 'true' 'true' 'true' 'false' 'false' 'false' 'false' 'false'
 'false']


## Adding and Removing data


In [31]:
arr1=np.array([2,3,4])
arr2=np.array([5,6,7])
combined=np.concatenate((arr1,arr2))
print('combined Array',combined)


combined Array [2 3 4 5 6 7]


In [34]:
##array compatibility
arr1=np.array([1,2,3])
arr2=np.array([3,4,5,6])
print('Compatibility of array ', arr1.shape==arr2.shape)

Compatibility of array  False


In [40]:
org_arr=np.array([[1,2],[3,4]])
new_row=np.array([4,5])
with_new_row=np.vstack((org_arr,new_row))
print('orginal array',org_arr)
print(' array with added row',with_new_row)

new_col=np.array([[2],[3]])
with_new_col=np.hstack((org_arr,new_col))
print('array with new column ',with_new_col)

orginal array [[1 2]
 [3 4]]
 array with added row [[1 2]
 [3 4]
 [4 5]]
array with new column  [[1 2 2]
 [3 4 3]]


## Delete Operation


In [42]:
array=np.array([1,2,3,4])
deleted=np.delete(array,2)
print('array after deletion',deleted)

array after deletion [1 2 4]
